### ISSUE TITLE
Error with yarn start

### ISSUE THREAD

**Issue by ddotx** [byumark/sam-library-frontend#2]
`Uncaught SyntaxError: The URL 'http:/sockjs-node' is invalid
    at new SockJS (sockjs.js:678)
    at new SockJSClient (SockJSClient.js:39)
    at initSocket (socket.js:20)
    at Object.<anonymous> (index.js:176)
    at Object.../../webpack-dev-server/client/index.js?http://[http://localhost]:3000 (index.js:45)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Object.1 (shared.js:120)
    at __webpack_require__ (bootstrap:726)
    at bootstrap:793`

**Comment by jerryno6** [comment]
Error with yarn start 
`D:\PROJECTS\GITHUB\SAM-demo\src\sam-library-frontend\node_modules\@babel\core\node_modules\source-map\lib\array-set.js:109
  throw new Error('No element indexed by ' + aIdx);
    at buildMappingData (D:\PROJECTS\GITHUB\SAM-demo\src\sam-library-frontend\node_modules\@babel\core\lib\transformation\file\merge-map.js:155:12)      
    at mergeSourceMap (D:\PROJECTS\GITHUB\SAM-demo\src\sam-library-frontend\node_modules\@babel\core\lib\transformation\file\merge-map.js:21:17)
    at generateCode (D:\PROJECTS\GITHUB\SAM-demo\src\sam-library-frontend\node_modules\@babel\core\lib\transformation\file\generate.js:74:39)
    at runSync (D:\PROJECTS\GITHUB\SAM-demo\src\sam-library-frontend\node_modules\@babel\core\lib\transformation\index.js:50:51)
    at transformSync (D:\PROJECTS\GITHUB\SAM-demo\src\sam-library-frontend\node_modules\@babel\core\lib\transform.js:43:38)    at Object.transform (D:\PROJECTS\GITHUB\SAM-demo\src\sam-library-frontend\node_modules\@babel\core\lib\transform.js:22:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by byumark** [comment]
It still works for me but I went ahead and upgrading several of the packages. Do you mind testing again? @jerryno6 

Sorry this response took so long, @ddotx . I must have missed your comment.

**Comment by jerryno6** [comment]
I've reinstalled windows 10, then
I tried the Readme.md again and I got this error while running `yarn install`

![image](https://user-images.githubusercontent.com/4426269/141603955-df94a5c4-e74a-475a-a0fb-1ff6f38a92ea.png)

I'm using node v16.13.0

**Comment by byumark** [comment]
@jerryno6 thanks for letting me know about that. That's a mistake on my part. I just pushed up an update that should work.

**Comment by jerryno6** [comment]
I finished this exercise a few weeks ago because Pluralsight only offered me 10 days free for learning. I just support you to make this repository better. This time, your code works. Thanks for the course. You can close this ticket. ^_^
